//! Integration coverage for `WorkspaceManager::merge_all` against a real,
//! throwaway git repo -- see DESIGN.md ("pact-vcs > merge_all").
use std::path::{Path, PathBuf};
use std::process::Command;

use pact_vcs::WorkspaceManager;
use uuid::Uuid;

fn run_git(dir: &Path, args: &[&str]) {
    let output = Command::new("git")
        .args(args)
        .current_dir(dir)
        .output()
        .unwrap_or_else(|err| panic!("failed to spawn `git {}`: {err}", args.join(" ")));
    assert!(
        output.status.success(),
        "`git {}` failed:\n{}",
        args.join(" "),
        String::from_utf8_lossy(&output.stderr)
    );
}

/// Creates a fresh temp git repo with two committed files: `src/index.ts`
/// (five lines, so an append at the end has real surrounding context and a
/// change to line 1 stays a well-separated edit) and `src/other.ts` (one
/// line, an entirely unrelated file). Returns the repo root.
fn init_repo() -> PathBuf {
    let root = std::env::temp_dir().join(format!("pact-vcs-merge-all-{}", Uuid::new_v4()));
    std::fs::create_dir_all(root.join("src")).unwrap();
    run_git(&root, &["init", "-q"]);
    run_git(&root, &["config", "user.email", "test@test.com"]);
    run_git(&root, &["config", "user.name", "test"]);
    std::fs::write(
        root.join("src/index.ts"),
        "export const L1 = 1;\nexport const L2 = 2;\nexport const L3 = 3;\n\
         export const L4 = 4;\nexport const L5 = 5;\n",
    )
    .unwrap();
    std::fs::write(root.join("src/other.ts"), "export const OTHER = 0;\n").unwrap();
    run_git(&root, &["add", "-A"]);
    run_git(&root, &["commit", "-q", "-m", "init"]);
    root
}

fn cleanup(root: &Path) {
    let _ = std::fs::remove_dir_all(root);
    if let Ok(state_dir) = WorkspaceManager::state_dir_for(root) {
        let _ = std::fs::remove_dir_all(state_dir);
    }
}

/// Same base as `init_repo`, plus `package.json` (one existing dependency)
/// and a stand-in `package-lock.json` -- used by the semantic-resolution
/// tests below.
fn init_repo_with_package_json() -> PathBuf {
    let root = init_repo();
    std::fs::write(
        root.join("package.json"),
        "{\n  \"name\": \"test\",\n  \"version\": \"1.0.0\",\n  \"dependencies\": {\n    \"a\": \"1.0.0\"\n  }\n}\n",
    )
    .unwrap();
    std::fs::write(
        root.join("package-lock.json"),
        "{\n  \"lockfileVersion\": 1\n}\n",
    )
    .unwrap();
    run_git(&root, &["add", "-A"]);
    run_git(&root, &["commit", "-q", "-m", "add package.json"]);
    root
}

fn init_repo_with_cargo_toml() -> PathBuf {
    let root = init_repo();
    std::fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"test\"\nversion = \"1.0.0\"\n\n[dependencies]\n# pinned, see issue #1\nanyhow = \"1\"\n",
    )
    .unwrap();
    std::fs::write(root.join("Cargo.lock"), "# This file is automatically @generated by Cargo.\nversion = 3\n").unwrap();
    run_git(&root, &["add", "-A"]);
    run_git(&root, &["commit", "-q", "-m", "add Cargo.toml"]);
    root
}

/// Same base as `init_repo`, plus a single-line `src/barrel.ts` -- used by
/// the `--union` test. See DESIGN.md ("pact-vcs > merge_all") for why a
/// single-line file is used deliberately.
fn init_repo_with_barrel() -> PathBuf {
    let root = init_repo();
    std::fs::write(root.join("src/barrel.ts"), "export {};\n").unwrap();
    run_git(&root, &["add", "-A"]);
    run_git(&root, &["commit", "-q", "-m", "add barrel"]);
    root
}

/// Same base as `init_repo`, plus a `src/plugins.ts` barrel with a sentinel
/// marker pair around a registration block, followed by a trailing
/// finalizer call -- the exact shape issue #87 was filed about: a plain
/// append-at-end lands new registrations after `finalize()`, not inside
/// the intended block.
fn init_repo_with_sentinel_barrel() -> PathBuf {
    let root = init_repo();
    std::fs::write(
        root.join("src/plugins.ts"),
        "// pact:union-start\n// pact:union-end\nfinalize();\n",
    )
    .unwrap();
    run_git(&root, &["add", "-A"]);
    run_git(&root, &["commit", "-q", "-m", "add plugins barrel"]);
    root
}

fn show(repo: &Path, spec: &str) -> String {
    let output = Command::new("git")
        .args(["show", spec])
        .current_dir(repo)
        .output()
        .unwrap();
    assert!(output.status.success(), "git show {spec} failed: {}", String::from_utf8_lossy(&output.stderr));
    String::from_utf8(output.stdout).unwrap()
}

#[test]
fn merge_all_merges_compatible_changes_and_skips_real_conflict() {
    let repo = init_repo();
    let manager = WorkspaceManager::open(&repo).unwrap();

    // See DESIGN.md ("pact-vcs > merge_all") for why this scenario is
    // shaped the way it is (confirmed by hand against real git first).
    let a = manager.create_workspace("append L6", None).unwrap();
    std::fs::write(
        a.path.join("src/index.ts"),
        "export const L1 = 1;\nexport const L2 = 2;\nexport const L3 = 3;\n\
         export const L4 = 4;\nexport const L5 = 5;\nexport const L6 = 6;\n",
    )
    .unwrap();

    let b = manager.create_workspace("bump OTHER", None).unwrap();
    std::fs::write(b.path.join("src/other.ts"), "export const OTHER = 99;\n").unwrap();

    let c = manager.create_workspace("bump L1 to 100", None).unwrap();
    std::fs::write(
        c.path.join("src/index.ts"),
        "export const L1 = 100;\nexport const L2 = 2;\nexport const L3 = 3;\n\
         export const L4 = 4;\nexport const L5 = 5;\n",
    )
    .unwrap();

    let d = manager.create_workspace("bump L1 to 200", None).unwrap();
    std::fs::write(
        d.path.join("src/index.ts"),
        "export const L1 = 200;\nexport const L2 = 2;\nexport const L3 = 3;\n\
         export const L4 = 4;\nexport const L5 = 5;\n",
    )
    .unwrap();

    let report = manager.merge_all(None, None, &[], None, None, None, false).unwrap();

    let merged_ids: Vec<&str> = report.merged.iter().map(|w| w.id.as_str()).collect();
    assert!(merged_ids.contains(&a.id.as_str()), "expected {} (well-separated append) to always merge cleanly", a.id);
    assert!(merged_ids.contains(&b.id.as_str()), "expected {} (unrelated file) to always merge cleanly", b.id);

    // C and D touch the same single file so they tie on the
    // smallest-changeset-first heuristic -- which merges first (and
    // therefore which one the *other* conflicts against) isn't specified.
    let c_merged = merged_ids.contains(&c.id.as_str());
    let d_merged = merged_ids.contains(&d.id.as_str());
    assert!(
        c_merged ^ d_merged,
        "expected exactly one of C/D (they conflict with each other) to merge, got merged={merged_ids:?}"
    );
    assert_eq!(report.merged.len(), 3, "expected A, B, and exactly one of C/D to merge, got {merged_ids:?}");

    assert_eq!(report.skipped.len(), 1, "expected exactly one skipped workspace");
    let skipped = &report.skipped[0];
    assert!(
        skipped.id == c.id || skipped.id == d.id,
        "expected the skipped workspace to be C or D, got {}", skipped.id
    );
    assert!(
        skipped.reason.contains("merge conflict"),
        "expected a merge-conflict reason, got: {}",
        skipped.reason
    );

    // The report's branch must actually exist in the repo, containing A and
    // B's changes, and the repo's own checkout must be untouched (still on
    // whatever branch `git init` created, not the integration branch).
    let branches = String::from_utf8(
        Command::new("git")
            .args(["branch", "--list", &report.target_branch])
            .current_dir(&repo)
            .output()
            .unwrap()
            .stdout,
    )
    .unwrap();
    assert!(
        branches.contains(&report.target_branch),
        "expected branch '{}' to exist after merge_all", report.target_branch
    );

    let current_branch = String::from_utf8(
        Command::new("git")
            .args(["branch", "--show-current"])
            .current_dir(&repo)
            .output()
            .unwrap()
            .stdout,
    )
    .unwrap();
    assert!(
        !current_branch.trim().is_empty() && current_branch.trim() != report.target_branch,
        "merge_all must not check out the integration branch in the repo's own working tree"
    );

    cleanup(&repo);
}

#[test]
fn merge_all_dry_run_touches_no_git_state() {
    let repo = init_repo();
    let manager = WorkspaceManager::open(&repo).unwrap();

    let a = manager.create_workspace("add chunk export", None).unwrap();
    std::fs::write(
        a.path.join("src/index.ts"),
        "export {};\nexport * from './chunk';\n",
    )
    .unwrap();

    let branches_before = String::from_utf8(
        Command::new("git").args(["branch"]).current_dir(&repo).output().unwrap().stdout,
    )
    .unwrap();

    let report = manager.merge_all(None, None, &[], None, None, None, true).unwrap();

    assert!(report.dry_run);
    assert!(report.merged.is_empty(), "dry run must not actually merge anything");
    assert_eq!(report.planned.len(), 1);
    assert_eq!(report.planned[0].id, a.id);

    let branches_after = String::from_utf8(
        Command::new("git").args(["branch"]).current_dir(&repo).output().unwrap().stdout,
    )
    .unwrap();
    assert_eq!(
        branches_before, branches_after,
        "dry run must not create the integration branch (or any other branch)"
    );

    cleanup(&repo);
}

/// Regression test for a real, serious finding from an outside R4
/// regression report (issue #194): `merge_all` used to log a WARN saying
/// it was "leaving out" a workspace whose auto-commit failed, but never
/// actually removed it from the batch -- so a failed auto-commit still
/// fell through to a real merge attempt against a branch with no new
/// commits (nothing to merge, since the intended changes never landed),
/// which trivially "succeeds" and gets reported as a clean `merged <id>`,
/// exit 0, on a branch silently byte-identical to base. Forces a real
/// `commit_all` failure via a `pre-commit` hook that always exits
/// non-zero (portable across platforms, unlike relying on a
/// Windows-specific filename-too-long error) rather than simulating it.
#[test]
fn merge_all_reports_skipped_not_merged_when_auto_commit_fails() {
    let repo = init_repo();
    let manager = WorkspaceManager::open(&repo).unwrap();

    let a = manager.create_workspace("add a change", None).unwrap();
    std::fs::write(a.path.join("src/other.ts"), "export const OTHER = 999;\n").unwrap();

    // Hooks are shared across every worktree of this repo (there's only
    // one `.git/hooks`), so this fails `git commit` for the one workspace
    // this test creates.
    let hooks_dir = repo.join(".git").join("hooks");
    std::fs::create_dir_all(&hooks_dir).unwrap();
    let hook_path = hooks_dir.join("pre-commit");
    std::fs::write(&hook_path, "#!/bin/sh\nexit 1\n").unwrap();
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(&hook_path).unwrap().permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(&hook_path, perms).unwrap();
    }

    let report = manager.merge_all(None, None, &[], None, None, None, false).unwrap();

    assert!(report.merged.is_empty(), "nothing should have been merged since the auto-commit failed");
    assert_eq!(report.skipped.len(), 1, "the workspace must show up as skipped, not silently dropped");
    assert_eq!(report.skipped[0].id, a.id);
    assert!(
        report.skipped[0].reason.contains("auto-commit"),
        "expected the skip reason to explain why, got: {}",
        report.skipped[0].reason
    );

    // The exact data-loss shape this bug produced: confirm the "merged"
    // branch is really byte-identical to base, not just that the report
    // says so.
    let target_tree = String::from_utf8(
        Command::new("git")
            .args(["rev-parse", &format!("{}^{{tree}}", report.target_branch)])
            .current_dir(&repo)
            .output()
            .unwrap()
            .stdout,
    )
    .unwrap();
    let base_tree = String::from_utf8(
        Command::new("git")
            .args(["rev-parse", &format!("{}^{{tree}}", report.base_commit)])
            .current_dir(&repo)
            .output()
            .unwrap()
            .stdout,
    )
    .unwrap();
    assert_eq!(target_tree, base_tree, "the target branch must not silently diverge from base when nothing was actually merged");

    cleanup(&repo);
}

/// Regression test for the risk-aware sequencing itself (issue #159), not
/// just `merge_risk_score` in isolation: a workspace touching only
/// `package.json` (one file, but central) must still be planned *after* a
/// workspace touching three unrelated plain files, even though the plain
/// changeset is larger by raw file count.
#[test]
fn merge_all_dry_run_sequences_a_central_file_touch_after_a_larger_plain_changeset() {
    let root = init_repo_with_package_json();
    let manager = WorkspaceManager::open(&root).unwrap();

    let central = manager.create_workspace("bump a dependency", None).unwrap();
    std::fs::write(
        central.path.join("package.json"),
        "{\n  \"name\": \"test\",\n  \"version\": \"1.0.0\",\n  \"dependencies\": {\n    \"a\": \"2.0.0\"\n  }\n}\n",
    )
    .unwrap();

    let plain = manager.create_workspace("add three new files", None).unwrap();
    std::fs::write(plain.path.join("a.ts"), "export const A = 1;\n").unwrap();
    std::fs::write(plain.path.join("b.ts"), "export const B = 1;\n").unwrap();
    std::fs::write(plain.path.join("c.ts"), "export const C = 1;\n").unwrap();

    let report = manager.merge_all(None, None, &[], None, None, None, true).unwrap();
    assert!(report.dry_run);
    assert_eq!(report.planned.len(), 2);
    assert_eq!(report.planned[0].id, plain.id, "the larger plain changeset should still be sequenced first");
    assert_eq!(report.planned[1].id, central.id, "the smaller but central-file change should be sequenced later");
    assert!(
        report.planned[1].risk_score > report.planned[0].risk_score,
        "expected the central-file workspace's risk score ({}) to exceed the plain one's ({})",
        report.planned[1].risk_score,
        report.planned[0].risk_score
    );

    cleanup(&root);
}

/// Regression test for issue #236: two workspaces sharing an edited file
/// with each other must be sequenced *after* an isolated workspace whose
/// changes touch nothing anyone else does, even though a plain
/// changed-file-count comparison alone wouldn't distinguish them.
#[test]
fn merge_all_dry_run_sequences_an_isolated_workspace_before_ones_sharing_a_file() {
    let root = init_repo();
    let manager = WorkspaceManager::open(&root).unwrap();

    let isolated = manager.create_workspace("touch only my own file", None).unwrap();
    std::fs::write(isolated.path.join("only_mine.ts"), "export const MINE = 1;\n").unwrap();

    let shares_a = manager.create_workspace("edit shared.ts (a)", None).unwrap();
    std::fs::write(shares_a.path.join("shared.ts"), "export const A = 1;\n").unwrap();

    let shares_b = manager.create_workspace("edit shared.ts (b)", None).unwrap();
    std::fs::write(shares_b.path.join("shared.ts"), "export const B = 1;\n").unwrap();

    let report = manager.merge_all(None, None, &[], None, None, None, true).unwrap();
    assert!(report.dry_run);
    assert_eq!(report.planned.len(), 3);
    assert_eq!(report.planned[0].id, isolated.id, "the isolated workspace must be sequenced first");
    let shares_ids: std::collections::HashSet<&str> = [report.planned[1].id.as_str(), report.planned[2].id.as_str()].into();
    assert!(shares_ids.contains(shares_a.id.as_str()) && shares_ids.contains(shares_b.id.as_str()));
    assert!(
        report.planned[1].risk_score > report.planned[0].risk_score,
        "expected a workspace sharing a file with another to outrank the isolated one"
    );

    cleanup(&root);
}

#[test]
fn merge_all_skips_workspace_whose_base_is_no_longer_an_ancestor() {
    let repo = init_repo();
    let manager = WorkspaceManager::open(&repo).unwrap();

    let a = manager.create_workspace("some change", None).unwrap();
    std::fs::write(a.path.join("src/index.ts"), "export const X = 1;\n").unwrap();

    // Rewrite the repo's own init commit so the SHA `a.base_commit` recorded
    // no longer exists on this branch's history at all -- simulating "HEAD
    // was reset/rebased since this workspace was created" without needing a
    // second, unrelated repo.
    run_git(&repo, &["commit", "--amend", "-q", "--allow-empty", "-m", "init (amended)"]);

    let report = manager.merge_all(None, None, &[], None, None, None, false).unwrap();

    assert!(report.merged.is_empty(), "workspace with a moved base must not be merged");
    assert_eq!(report.skipped.len(), 1);
    assert_eq!(report.skipped[0].id, a.id);
    assert!(
        report.skipped[0].reason.contains("no longer part of this branch's history"),
        "expected a moving-base reason, got: {}",
        report.skipped[0].reason
    );

    cleanup(&repo);
}

#[test]
fn merge_all_auto_resolves_package_json_dependency_conflict() {
    let repo = init_repo_with_package_json();
    let manager = WorkspaceManager::open(&repo).unwrap();

    // Confirmed by hand against real git first -- see DESIGN.md
    // ("pact-vcs > Semantic auto-resolution").
    let a = manager.create_workspace("add dep b", None).unwrap();
    std::fs::write(
        a.path.join("package.json"),
        "{\n  \"name\": \"test\",\n  \"version\": \"1.0.0\",\n  \"dependencies\": {\n    \"a\": \"1.0.0\",\n    \"b\": \"2.0.0\"\n  }\n}\n",
    )
    .unwrap();

    let b = manager.create_workspace("add dep c", None).unwrap();
    std::fs::write(
        b.path.join("package.json"),
        "{\n  \"name\": \"test\",\n  \"version\": \"1.0.0\",\n  \"dependencies\": {\n    \"a\": \"1.0.0\",\n    \"c\": \"3.0.0\"\n  }\n}\n",
    )
    .unwrap();

    let report = manager.merge_all(None, None, &[], None, None, None, false).unwrap();

    assert_eq!(report.skipped.len(), 0, "expected both to merge via JSON-aware auto-resolution, got skipped={:?}", report.skipped);
    assert_eq!(report.merged.len(), 2);

    // One of the two merges is a plain clean merge (whichever lands first
    // on an untouched package.json); the other must go through -- and
    // report -- the JSON-aware resolver.
    let auto_resolved_count = report
        .merged
        .iter()
        .filter(|w| w.auto_resolved.iter().any(|f| f == "package.json"))
        .count();
    assert_eq!(auto_resolved_count, 1, "expected exactly one merge to need package.json auto-resolution");

    let content = show(&repo, &format!("{}:package.json", report.target_branch));
    let value: serde_json::Value = serde_json::from_str(&content).expect("merged package.json must be valid JSON");
    let deps = value.get("dependencies").and_then(|d| d.as_object()).expect("dependencies object");
    assert_eq!(deps.get("a").and_then(|v| v.as_str()), Some("1.0.0"));
    assert_eq!(deps.get("b").and_then(|v| v.as_str()), Some("2.0.0"));
    assert_eq!(deps.get("c").and_then(|v| v.as_str()), Some("3.0.0"));

    cleanup(&repo);
}

/// Regression test for issue #29: the JSON-aware package.json resolver used
/// to reserialize through a BTreeMap-backed `serde_json::Value`, which
/// alphabetized every top-level key (`dependencies` before `name`) and
/// hardcoded 2-space indent regardless of the file's own convention. Uses a
/// 4-space-indented file with the full standard npm key set, deliberately
/// not already alphabetical, so either regression would show up.
#[test]
fn merge_all_package_json_merge_preserves_key_order_and_indent() {
    let repo = init_repo();
    let base = "{\n    \"name\": \"widget\",\n    \"version\": \"1.0.0\",\n    \
                \"description\": \"a widget\",\n    \"main\": \"index.js\",\n    \
                \"scripts\": {\n        \"test\": \"node test.js\"\n    },\n    \
                \"dependencies\": {\n        \"a\": \"1.0.0\"\n    },\n    \
                \"devDependencies\": {}\n}\n";
    std::fs::write(repo.join("package.json"), base).unwrap();
    run_git(&repo, &["add", "-A"]);
    run_git(&repo, &["commit", "-q", "-m", "add 4-space package.json"]);

    let manager = WorkspaceManager::open(&repo).unwrap();

    let a = manager.create_workspace("add dep b", None).unwrap();
    std::fs::write(
        a.path.join("package.json"),
        base.replace("\"a\": \"1.0.0\"\n", "\"a\": \"1.0.0\",\n        \"b\": \"2.0.0\"\n"),
    )
    .unwrap();

    let b = manager.create_workspace("add dep c", None).unwrap();
    std::fs::write(
        b.path.join("package.json"),
        base.replace("\"a\": \"1.0.0\"\n", "\"a\": \"1.0.0\",\n        \"c\": \"3.0.0\"\n"),
    )
    .unwrap();

    let report = manager.merge_all(None, None, &[], None, None, None, false).unwrap();
    assert_eq!(report.skipped.len(), 0, "expected both to merge via JSON-aware auto-resolution, got skipped={:?}", report.skipped);

    let content = show(&repo, &format!("{}:package.json", report.target_branch));

    let value: serde_json::Value = serde_json::from_str(&content).expect("merged package.json must be valid JSON");
    let keys: Vec<String> = value.as_object().unwrap().keys().cloned().collect();
    assert_eq!(
        keys,
        vec!["name", "version", "description", "main", "scripts", "dependencies", "devDependencies"],
        "top-level key order must be preserved across a merge, got {keys:?}\nfull content:\n{content}"
    );

    assert!(
        content.contains("\n    \"name\": \"widget\""),
        "expected the file's own 4-space indent to be preserved, got:\n{content}"
    );
    assert!(content.contains("\"a\": \"1.0.0\""));
    assert!(content.contains("\"b\": \"2.0.0\""));
    assert!(content.contains("\"c\": \"3.0.0\""));

    cleanup(&repo);
}

/// Regression test for issue #57: a real Windows footgun where PowerShell's
/// `Out-File -Encoding utf8` (and other common tooling) writes a leading
/// UTF-8 BOM by default. `serde_json::from_str` rejects a BOM outright, so
/// before the fix this fell through to a real conflict instead of the
/// JSON-aware auto-resolve.
#[test]
fn merge_all_package_json_merge_handles_utf8_bom() {
    let repo = init_repo();
    const BOM: &str = "\u{FEFF}";
    let base = "{\n  \"name\": \"widget\",\n  \"version\": \"1.0.0\",\n  \
                \"dependencies\": {\n    \"a\": \"1.0.0\"\n  }\n}\n";
    std::fs::write(repo.join("package.json"), format!("{BOM}{base}")).unwrap();
    run_git(&repo, &["add", "-A"]);
    run_git(&repo, &["commit", "-q", "-m", "add BOM'd package.json"]);

    let manager = WorkspaceManager::open(&repo).unwrap();

    let a = manager.create_workspace("add dep b", None).unwrap();
    std::fs::write(
        a.path.join("package.json"),
        format!("{BOM}{}", base.replace("\"a\": \"1.0.0\"\n", "\"a\": \"1.0.0\",\n    \"b\": \"2.0.0\"\n")),
    )
    .unwrap();

    let b = manager.create_workspace("add dep c", None).unwrap();
    std::fs::write(
        b.path.join("package.json"),
        format!("{BOM}{}", base.replace("\"a\": \"1.0.0\"\n", "\"a\": \"1.0.0\",\n    \"c\": \"3.0.0\"\n")),
    )
    .unwrap();

    let report = manager.merge_all(None, None, &[], None, None, None, false).unwrap();
    assert_eq!(
        report.skipped.len(),
        0,
        "a BOM'd package.json must still auto-resolve via the JSON-aware merge, got skipped={:?}",
        report.skipped
    );

    let content = show(&repo, &format!("{}:package.json", report.target_branch));
    assert!(
        content.starts_with('\u{FEFF}'),
        "the committed package.json had a BOM, so the merged output must preserve it (issue #79), got:\n{content:?}"
    );
    let value: serde_json::Value =
        serde_json::from_str(content.trim_start_matches('\u{FEFF}')).expect("merged package.json must be valid JSON");
    let deps = value.get("dependencies").and_then(|d| d.as_object()).expect("dependencies object");
    assert_eq!(deps.get("a").and_then(|v| v.as_str()), Some("1.0.0"));
    assert_eq!(deps.get("b").and_then(|v| v.as_str()), Some("2.0.0"));
    assert_eq!(deps.get("c").and_then(|v| v.as_str()), Some("3.0.0"));

    cleanup(&repo);
}

/// Regression test for issue #276: a reproducible, in-repo version of the
/// real-world benchmark issue #268 reported by hand -- N agents, one
/// file, disjoint regions, assert every expected value lands in the
/// merged tree with zero conflicts. That report used 5 real Copilot
/// agents (4 editing the same root `package.json` in disjoint regions,
/// 1 editing a second manifest) and got 13/13 expected changes, 0
/// conflicts; this reconstructs the same *shape* deterministically with
/// 5 simulated workspaces (direct `create_workspace` + file writes, the
/// same technique every other test in this file already uses -- no real
/// agent CLI needed, since what's under test is `merge_all`'s own
/// correctness, not anything about how a workspace's changes got there).
///
/// Deliberately placed here rather than in `pact-cli`'s `#[ignore]`d
/// slow-integration tier (issue #240): unlike that tier's tests, this one
/// needs no real dependency install or concurrency contention -- it's the
/// same fast, deterministic shape as every other JSON-merge test in this
/// file, just scaled from 2 workspaces to 5, so it belongs in the default
/// `cargo test --workspace` run like the rest of them.
///
/// Deliberately uses `PackageJsonResolver`'s 4 already-supported
/// dependency-block keys (`dependencies`/`devDependencies`/
/// `peerDependencies`/`optionalDependencies`), not the real report's
/// `overrides` key -- `overrides` isn't one of `PACKAGE_JSON_DEP_KEYS`,
/// so a synthetic conflict built around it wouldn't exercise JSON-aware
/// resolution at all (it would either fall through to a real conflict or
/// pass by accident via a clean plain-git merge, neither of which proves
/// what this test exists to prove).
#[test]
fn merge_all_correctly_merges_four_agents_disjoint_edits_to_one_package_json_plus_a_second_manifest() {
    let repo = init_repo();
    std::fs::write(
        repo.join("package.json"),
        "{\n  \"name\": \"bench\",\n  \"version\": \"1.0.0\",\n  \"dependencies\": {},\n  \
         \"devDependencies\": {},\n  \"peerDependencies\": {},\n  \"optionalDependencies\": {}\n}\n",
    )
    .unwrap();
    std::fs::create_dir_all(repo.join("jobs/reminders")).unwrap();
    std::fs::write(
        repo.join("jobs/reminders/package.json"),
        "{\n  \"name\": \"reminders\",\n  \"version\": \"1.0.0\",\n  \"dependencies\": {}\n}\n",
    )
    .unwrap();
    run_git(&repo, &["add", "-A"]);
    run_git(&repo, &["commit", "-q", "-m", "add bench package.json + second manifest"]);

    let manager = WorkspaceManager::open(&repo).unwrap();

    // 4 agents, 4 disjoint blocks of the same root package.json.
    let blocks = [
        ("dependencies", "a", "1.0.0"),
        ("devDependencies", "b", "2.0.0"),
        ("peerDependencies", "c", "3.0.0"),
        ("optionalDependencies", "d", "4.0.0"),
    ];
    let mut workspace_ids = Vec::new();
    for (block, name, version) in blocks {
        let ws = manager.create_workspace(&format!("add {name} to {block}"), None).unwrap();
        std::fs::write(
            ws.path.join("package.json"),
            format!(
                "{{\n  \"name\": \"bench\",\n  \"version\": \"1.0.0\",\n  \"dependencies\": {},\n  \
                 \"devDependencies\": {},\n  \"peerDependencies\": {},\n  \"optionalDependencies\": {}\n}}\n",
                if block == "dependencies" { format!("{{\n    \"{name}\": \"{version}\"\n  }}") } else { "{}".to_string() },
                if block == "devDependencies" { format!("{{\n    \"{name}\": \"{version}\"\n  }}") } else { "{}".to_string() },
                if block == "peerDependencies" { format!("{{\n    \"{name}\": \"{version}\"\n  }}") } else { "{}".to_string() },
                if block == "optionalDependencies" { format!("{{\n    \"{name}\": \"{version}\"\n  }}") } else { "{}".to_string() },
            ),
        )
        .unwrap();
        workspace_ids.push(ws.id);
    }

    // 5th agent, a second, entirely unrelated manifest.
    let e = manager.create_workspace("add e to jobs/reminders", None).unwrap();
    std::fs::write(
        e.path.join("jobs/reminders/package.json"),
        "{\n  \"name\": \"reminders\",\n  \"version\": \"1.0.0\",\n  \"dependencies\": {\n    \"e\": \"5.0.0\"\n  }\n}\n",
    )
    .unwrap();
    workspace_ids.push(e.id);

    let report = manager.merge_all(None, None, &[], None, None, None, false).unwrap();

    assert!(report.conflicted.is_empty(), "expected zero unresolved conflicts, got: {:?}", report.conflicted);
    assert!(report.skipped.is_empty(), "expected zero skipped workspaces, got: {:?}", report.skipped);
    assert_eq!(report.merged.len(), 5, "expected all 5 workspaces to merge");

    // The real report's headline: MORE than one workspace needed
    // JSON-aware auto-resolution -- proving this holds at N-agent scale,
    // not just the 2-workspace "exactly one" case the other tests above
    // already cover.
    let auto_resolved_count =
        report.merged.iter().filter(|w| w.auto_resolved.iter().any(|f| f == "package.json")).count();
    assert!(
        auto_resolved_count >= 2,
        "expected multiple workspaces to need JSON-aware auto-resolution on the shared package.json, got {auto_resolved_count}"
    );

    let content = show(&repo, &format!("{}:package.json", report.target_branch));
    let value: serde_json::Value = serde_json::from_str(&content).expect("merged package.json must be valid JSON");
    for (block, name, version) in blocks {
        let block_obj = value.get(block).and_then(|b| b.as_object()).unwrap_or_else(|| panic!("missing block {block}"));
        assert_eq!(
            block_obj.get(name).and_then(|v| v.as_str()),
            Some(version),
            "expected {name}: {version} in {block}, got: {content}"
        );
    }

    let second_manifest = show(&repo, &format!("{}:jobs/reminders/package.json", report.target_branch));
    let second_value: serde_json::Value =
        serde_json::from_str(&second_manifest).expect("merged second manifest must be valid JSON");
    let second_deps = second_value.get("dependencies").and_then(|d| d.as_object()).expect("dependencies object");
    assert_eq!(second_deps.get("e").and_then(|v| v.as_str()), Some("5.0.0"), "got: {second_manifest}");

    cleanup(&repo);
}

/// Real end-to-end coverage for issue #272's `TomlManifestResolver`,
/// through the full `merge_all` path (not just the resolver in
/// isolation) -- mirrors `merge_all_auto_resolves_package_json_dependency_conflict`
/// above, for Cargo.toml instead of package.json. Also proves the
/// resolver's comment-preservation promise survives real 3-way conflict
/// staging, not just a direct `resolve()` call.
#[test]
fn merge_all_auto_resolves_cargo_toml_dependency_conflict() {
    let repo = init_repo_with_cargo_toml();
    let manager = WorkspaceManager::open(&repo).unwrap();

    let a = manager.create_workspace("add dep serde", None).unwrap();
    std::fs::write(
        a.path.join("Cargo.toml"),
        "[package]\nname = \"test\"\nversion = \"1.0.0\"\n\n[dependencies]\n# pinned, see issue #1\nanyhow = \"1\"\nserde = \"1\"\n",
    )
    .unwrap();

    let b = manager.create_workspace("add dep uuid", None).unwrap();
    std::fs::write(
        b.path.join("Cargo.toml"),
        "[package]\nname = \"test\"\nversion = \"1.0.0\"\n\n[dependencies]\n# pinned, see issue #1\nanyhow = \"1\"\nuuid = \"1\"\n",
    )
    .unwrap();

    let report = manager.merge_all(None, None, &[], None, None, None, false).unwrap();
    assert_eq!(
        report.skipped.len(),
        0,
        "expected both to merge via TOML-aware auto-resolution, got skipped={:?}",
        report.skipped
    );
    assert_eq!(report.merged.len(), 2);

    let auto_resolved_count = report
        .merged
        .iter()
        .filter(|w| w.auto_resolved.iter().any(|f| f == "Cargo.toml"))
        .count();
    assert_eq!(auto_resolved_count, 1, "expected exactly one merge to need Cargo.toml auto-resolution");

    let content = show(&repo, &format!("{}:Cargo.toml", report.target_branch));
    assert!(content.contains("serde"), "got: {content}");
    assert!(content.contains("uuid"), "got: {content}");
    assert!(
        content.contains("# pinned, see issue #1"),
        "expected the unrelated comment to survive a real 3-way merge, got: {content}"
    );

    cleanup(&repo);
}

#[test]
fn merge_all_union_resolves_matched_file_conflict() {
    let repo = init_repo_with_barrel();
    let manager = WorkspaceManager::open(&repo).unwrap();

    let a = manager.create_workspace("export chunk", None).unwrap();
    std::fs::write(a.path.join("src/barrel.ts"), "export {};\nexport * from './chunk';\n").unwrap();

    let b = manager.create_workspace("export omit", None).unwrap();
    std::fs::write(b.path.join("src/barrel.ts"), "export {};\nexport * from './omit';\n").unwrap();

    let report = manager
        .merge_all(None, None, &["src/barrel.ts".to_string()], None, None, None, false)
        .unwrap();

    assert_eq!(report.skipped.len(), 0, "expected both to merge via --union, got skipped={:?}", report.skipped);
    assert_eq!(report.merged.len(), 2);

    let auto_resolved_count = report
        .merged
        .iter()
        .filter(|w| w.auto_resolved.iter().any(|f| f == "src/barrel.ts"))
        .count();
    assert_eq!(auto_resolved_count, 1, "expected exactly one merge to need the union resolver");

    let content = show(&repo, &format!("{}:src/barrel.ts", report.target_branch));
    assert!(content.contains("export * from './chunk';"));
    assert!(content.contains("export * from './omit';"));

    cleanup(&repo);
}

/// Real, end-to-end regression coverage for issue #87's sentinel-marker
/// insertion mode, through the actual git merge pipeline (not just the
/// resolver in isolation) -- three workspaces sequentially merged, each
/// registering a different plugin inside the marked block. Before this
/// fix, only the first workspace's addition would land inside
/// `pact:union-start`/`-end`; the second and third would land after
/// `finalize()` instead.
#[test]
fn merge_all_union_inserts_before_sentinel_end_marker_across_three_workspaces() {
    let repo = init_repo_with_sentinel_barrel();
    let manager = WorkspaceManager::open(&repo).unwrap();

    let a = manager.create_workspace("register a", None).unwrap();
    std::fs::write(
        a.path.join("src/plugins.ts"),
        "// pact:union-start\nregister('a');\n// pact:union-end\nfinalize();\n",
    )
    .unwrap();

    let b = manager.create_workspace("register b", None).unwrap();
    std::fs::write(
        b.path.join("src/plugins.ts"),
        "// pact:union-start\nregister('b');\n// pact:union-end\nfinalize();\n",
    )
    .unwrap();

    let c = manager.create_workspace("register c", None).unwrap();
    std::fs::write(
        c.path.join("src/plugins.ts"),
        "// pact:union-start\nregister('c');\n// pact:union-end\nfinalize();\n",
    )
    .unwrap();

    let report = manager
        .merge_all(None, None, &["src/plugins.ts".to_string()], None, None, None, false)
        .unwrap();

    assert_eq!(report.skipped.len(), 0, "expected all three to merge via --union, got skipped={:?}", report.skipped);
    assert_eq!(report.merged.len(), 3);

    let content = show(&repo, &format!("{}:src/plugins.ts", report.target_branch));
    assert!(content.contains("register('a');"));
    assert!(content.contains("register('b');"));
    assert!(content.contains("register('c');"));

    let end_marker_pos = content.find("pact:union-end").expect("end marker must survive the merge");
    let finalize_pos = content.find("finalize();").expect("finalizer must survive the merge");
    for name in ["register('a');", "register('b');", "register('c');"] {
        let pos = content.find(name).unwrap_or_else(|| panic!("expected {name} in merged content:\n{content}"));
        assert!(pos < end_marker_pos, "expected {name} before the end marker, got:\n{content}");
    }
    assert!(end_marker_pos < finalize_pos, "expected the end marker before the finalizer, got:\n{content}");

    cleanup(&repo);
}

#[test]
fn merge_all_never_auto_resolves_lockfiles_even_with_matching_union_glob() {
    let repo = init_repo_with_package_json();
    let manager = WorkspaceManager::open(&repo).unwrap();

    let a = manager.create_workspace("touch lockfile a", None).unwrap();
    std::fs::write(
        a.path.join("package-lock.json"),
        "{\n  \"lockfileVersion\": 1,\n  \"a\": true\n}\n",
    )
    .unwrap();

    let b = manager.create_workspace("touch lockfile b", None).unwrap();
    std::fs::write(
        b.path.join("package-lock.json"),
        "{\n  \"lockfileVersion\": 1,\n  \"b\": true\n}\n",
    )
    .unwrap();

    // Even with an explicit --union match on the lockfile, NEVER_AUTO_RESOLVE
    // must win -- a real conflict here always stays a real conflict.
    let report = manager
        .merge_all(None, None, &["package-lock.json".to_string()], None, None, None, false)
        .unwrap();

    assert_eq!(report.merged.len(), 1, "expected exactly one of the two to merge cleanly");
    assert_eq!(report.skipped.len(), 1, "expected the other to stay a real, unresolved conflict");
    assert!(report.skipped[0].reason.contains("merge conflict"));

    cleanup(&repo);
}

/// Regression test for a real Windows shakedown finding: two agents each
/// append a disjoint export to the same CommonJS barrel and its
/// `module.exports` line. Both sides touch the *same* last line
/// differently, so git's plain 3-way merge always conflicts here (confirmed
/// by hand, same lesson as `init_repo_with_barrel`'s doc comment) -- and
/// the union resolver must recognize the merged result would carry two
/// `module.exports =` assignments (second silently wins) and refuse it,
/// rather than reporting a broken merge as `auto-resolved`.
#[test]
fn merge_all_union_rejects_conflicting_module_exports() {
    let repo = init_repo();
    std::fs::write(
        repo.join("src/barrel.js"),
        "const { add } = require('./add');\nconst { sub } = require('./sub');\nmodule.exports = { add, sub };\n",
    )
    .unwrap();
    run_git(&repo, &["add", "-A"]);
    run_git(&repo, &["commit", "-q", "-m", "add js barrel"]);

    let manager = WorkspaceManager::open(&repo).unwrap();

    let a = manager.create_workspace("add mul", None).unwrap();
    std::fs::write(
        a.path.join("src/barrel.js"),
        "const { add } = require('./add');\nconst { sub } = require('./sub');\n\
         const { mul } = require('./mul');\nmodule.exports = { add, sub, mul };\n",
    )
    .unwrap();

    let b = manager.create_workspace("add div", None).unwrap();
    std::fs::write(
        b.path.join("src/barrel.js"),
        "const { add } = require('./add');\nconst { sub } = require('./sub');\n\
         const { div } = require('./div');\nmodule.exports = { add, sub, div };\n",
    )
    .unwrap();

    let report = manager
        .merge_all(None, None, &["src/barrel.js".to_string()], None, None, None, false)
        .unwrap();

    assert_eq!(report.merged.len(), 1, "expected exactly one of the two to merge cleanly");
    assert_eq!(
        report.skipped.len(),
        1,
        "a union merge that would carry two `module.exports =` statements must stay a real conflict, not be silently auto-resolved -- got merged={:?} skipped={:?}",
        report.merged,
        report.skipped
    );
    assert!(report.skipped[0].reason.contains("merge conflict"));

    cleanup(&repo);
}

#[test]
fn merge_all_accepts_a_stub_arbiter_resolution() {
    let repo = init_repo();
    let manager = WorkspaceManager::open(&repo).unwrap();

    let c = manager.create_workspace("bump L1 to 100", None).unwrap();
    std::fs::write(
        c.path.join("src/index.ts"),
        "export const L1 = 100;\nexport const L2 = 2;\nexport const L3 = 3;\n\
         export const L4 = 4;\nexport const L5 = 5;\n",
    )
    .unwrap();
    let d = manager.create_workspace("bump L1 to 200", None).unwrap();
    std::fs::write(
        d.path.join("src/index.ts"),
        "export const L1 = 200;\nexport const L2 = 2;\nexport const L3 = 3;\n\
         export const L4 = 4;\nexport const L5 = 5;\n",
    )
    .unwrap();

    // Stands in for pact-core's real Arbiter closure (which would spawn an
    // agent and run a test command) -- proves the wiring end to end
    // (unresolved files reach the closure, its resolution gets staged and
    // committed, `arbiter_resolved` is reported) without spawning a real,
    // billed agent.
    let resolver = |worktree_path: &Path, _task_text: &str, files: &[String]| -> Vec<String> {
        for file in files {
            std::fs::write(
                worktree_path.join(file),
                "export const L1 = 999;\nexport const L2 = 2;\nexport const L3 = 3;\n\
                 export const L4 = 4;\nexport const L5 = 5;\n",
            )
            .unwrap();
            let add = Command::new("git").args(["add", "--", file]).current_dir(worktree_path).output();
            assert!(matches!(add, Ok(o) if o.status.success()));
        }
        files.to_vec()
    };

    let report = manager.merge_all(None, None, &[], Some(&resolver), None, None, false).unwrap();

    assert_eq!(report.skipped.len(), 0, "expected the stub arbiter to resolve the conflict, got skipped={:?}", report.skipped);
    assert_eq!(report.merged.len(), 2);
    let arbiter_resolved_count = report
        .merged
        .iter()
        .filter(|w| w.arbiter_resolved.iter().any(|f| f == "src/index.ts"))
        .count();
    assert_eq!(arbiter_resolved_count, 1, "expected exactly one merge to have needed the arbiter");

    let content = show(&repo, &format!("{}:src/index.ts", report.target_branch));
    assert!(content.contains("export const L1 = 999;"));

    cleanup(&repo);
}

#[test]
fn merge_all_still_aborts_when_arbiter_declines() {
    let repo = init_repo();
    let manager = WorkspaceManager::open(&repo).unwrap();

    let c = manager.create_workspace("bump L1 to 100", None).unwrap();
    std::fs::write(
        c.path.join("src/index.ts"),
        "export const L1 = 100;\nexport const L2 = 2;\nexport const L3 = 3;\n\
         export const L4 = 4;\nexport const L5 = 5;\n",
    )
    .unwrap();
    let d = manager.create_workspace("bump L1 to 200", None).unwrap();
    std::fs::write(
        d.path.join("src/index.ts"),
        "export const L1 = 200;\nexport const L2 = 2;\nexport const L3 = 3;\n\
         export const L4 = 4;\nexport const L5 = 5;\n",
    )
    .unwrap();

    // A "verification failed" stub -- e.g. its test command didn't pass --
    // always declines regardless of input. The merge must still be aborted
    // and reported as a real conflict, exactly as if Arbiter weren't
    // configured at all.
    let resolver = |_worktree_path: &Path, _task_text: &str, _files: &[String]| -> Vec<String> { Vec::new() };

    let report = manager.merge_all(None, None, &[], Some(&resolver), None, None, false).unwrap();

    assert_eq!(report.merged.len(), 1, "expected exactly one of the two to merge cleanly");
    assert_eq!(report.skipped.len(), 1, "expected the other to stay a real conflict when arbiter declines");

    cleanup(&repo);
}

/// Regression test for issue #78: a workspace meta JSON file with a leading
/// UTF-8 BOM (e.g. hand-edited via PowerShell 5.1's `Set-Content -Encoding
/// utf8`, which writes one by default) used to crash `list_workspaces`/
/// `get_workspace` with `expected value at line 1 column 1` -- neither
/// applied the `strip_bom` helper the codebase already had for this exact
/// problem in `read_conflict_stage` (issue #57).
#[test]
fn list_workspaces_and_get_workspace_tolerate_a_bom_in_meta_json() {
    let repo = init_repo();
    let manager = WorkspaceManager::open(&repo).unwrap();
    let ws = manager.create_workspace("some task", None).unwrap();

    let meta_path = manager.state_dir().join("meta").join(format!("{}.json", ws.id));
    let original = std::fs::read_to_string(&meta_path).unwrap();
    std::fs::write(&meta_path, format!("\u{FEFF}{original}")).unwrap();

    let workspaces = manager.list_workspaces().expect("list_workspaces must tolerate a BOM'd meta file");
    assert_eq!(workspaces.len(), 1);
    assert_eq!(workspaces[0].id, ws.id);

    let fetched = manager.get_workspace(&ws.id).expect("get_workspace must tolerate a BOM'd meta file");
    assert_eq!(fetched.id, ws.id);

    cleanup(&repo);
}
